services:
  app:
    build: .
    ports:
      - "8081:80"
    volumes:
      - .:/var/www/html
      - vendor_data:/var/www/html/vendor
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    env_file:
      - docker.env

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Evolvus*123
      MYSQL_DATABASE: project_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  mysql_data:
  vendor_data: 