version: '3.8'

services:
  app:
    image: php:8.1-apache
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    env_file:
      - docker.env
    command: >
      bash -c "
        apt-get update && apt-get install -y 
          libzip-dev 
          libpng-dev 
          libjpeg-dev 
          libfreetype6-dev 
          libxml2-dev 
          libcurl4-openssl-dev 
          git 
          unzip &&
        docker-php-ext-install 
          pdo_mysql 
          zip 
          gd 
          curl 
          xml &&
        curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
        composer install --no-dev &&
        cp docker.env .env &&
        chown -R www-data:www-data /var/www/html &&
        apache2-foreground
      "

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: Evolvus*123
      MYSQL_DATABASE: project_management
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  mysql_data: 