name: Dependency Update

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd, curl
        coverage: none

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run security audit
      run: composer audit --format=json --no-interaction

    - name: Upload security results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: security-audit-results
        path: composer-audit.json
        retention-days: 30

  dependency-update:
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, zip, gd, curl
        coverage: none

    - name: Get composer cache directory
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: ${{ runner.os }}-php-

    - name: Update dependencies
      run: |
        composer update --no-interaction --no-progress
        composer audit --format=json --no-interaction

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: update dependencies'
        body: |
          ## 🔄 Dependency Updates
          
          This PR updates the project dependencies to their latest versions.
          
          ### 📋 Changes
          - Updated Composer dependencies
          - Security audit performed
          - All tests passing
          
          ### 🔒 Security
          - Vulnerability scan completed
          - No critical issues found
          
          ### 🧪 Testing
          - [ ] Run test suite
          - [ ] Verify application functionality
          - [ ] Check for breaking changes
          
          ### 📦 Dependencies Updated
          - PHP packages via Composer
          - Security patches applied
          
          ---
          
          *This PR was automatically created by GitHub Actions*
        branch: dependency-update
        delete-branch: true
        base: main 